### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by steveoh** [gregbunce/NextGen911UtahGISDataLoader#1]
Version numbers do not belong in repository names. Git and github expose [tags](https://stackoverflow.com/a/18223354/352432) and I suggest using those along with [semver](http://semver.org) :) 🚀

**Comment by gregbunce** [comment]
agreed with the recommendation and removed version number from repo name - and considering adding a "release" number using semantic versioning to manage releases or just use pro sdk api version instead.  gracias amigo!
